# Generated by Django 2.2.2 on 2019-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0003_auto_20190619_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='person_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='profile_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
