# Generated by Django 2.2.2 on 2019-07-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0006_auto_20190628_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
