# Generated by Django 2.2.2 on 2019-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0007_scraplocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='scrape_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
