# Generated by Django 2.2.2 on 2019-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0008_categories_scrape_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='scrape_status',
        ),
    ]
